# Generated by Django 4.2.7 on 2023-12-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
        ('pincode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='zone_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zone.zone'),
        ),
    ]
