# Generated by Django 4.2.7 on 2023-12-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pincode', '0002_pincode_zone_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pincode',
            old_name='zone_name',
            new_name='zone_id',
        ),
    ]
